# Generated by Django 4.1.4 on 2022-12-23 19:49

import common.utils.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_image_url_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=256, null=True, upload_to=common.utils.file.upload_to),
        ),
    ]
